---
title: "2003 European heatwave"
output: html_document
date: "2024-08-05"
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

# load libraries
library(here)
library(tidyverse)
library(ggplot2)
library(gridExtra)

```

Supplementary analysis comparing cross-sector shock impacts across sectors with [Schewe et al., 2019 *Nature Communications*](https://www.nature.com/articles/s41467-019-08745-6).

## Shocks from ISIMIP3b

```{r 2003, echo=FALSE, warning=FALSE, message=FALSE}
xx <- read_csv("/Users/auroremaureaud/Library/CloudStorage/Dropbox/Minerva 2021 Climate Politics/Aurore/Resource synthesis/future_resource_change/data/short-term_change/countries_shocks_time_series_1985-2015.csv")%>% 
   filter(!output_variable %in% c("tws","tcb","ptotww"),
          experiment_climate == "ssp585") %>%
   data.frame() %>% 
  filter(regions %in% c("Austria","Bulgaria","Czech Republic","Denmark","France","Germany","Greece","Hungary","Italy","Romania","Poland","Portugal","Spain"),
         years == 2003) %>% 
  group_by(regions, climate_model, output_variable) %>% 
  summarize(shock_down = mean(shock_down, na.rm=T),
            shock = mean(shock, na.rm=T),
            show_up = mean(shock_up, na.rm=T)) %>% 
  pivot_longer(4:6, names_to = "type", values_to = "proportion")

ggplot(xx, aes(x = regions, y = proportion, fill = type)) + geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("grey","red","mediumseagreen")) +
  facet_wrap(~ output_variable) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, hjust=0))

```

